FROM ruby:2.5
# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1
# RUN gem install bundler --version '=1.16.2'
RUN apt-get update -qq && apt-get install -y mysql-client build-essential libpq-dev nodejs 

RUN mkdir /ursus
WORKDIR /ursus
COPY ursus/Gemfile /ursus/Gemfile
COPY ursus/Gemfile.lock /ursus/Gemfile.lock
RUN bundle install
COPY ./ursus /ursus
CMD ["bundle exec rails server"]
